<?php
$lang = array(
	'gdloadout_nav_loadouts'              => 'Loadouts',
	'gdloadout_hub_title'                 => 'Loadouts',
	'gdloadout_hub_empty'                 => 'No community builds yet — the loadout builder is coming soon.',
	'menutab__gdloadout_icon'             => 'layer-group',
	'menu__gdloadout_loadouts_hub'        => 'Loadouts',
	'menu__gdloadout_manage_limits'       => 'Limits',
	'r__limits_manage'                    => 'Manage loadout limits',
	'gdloadout_limits_title'              => 'Loadout Limits',
	'gdloadout_limits_desc'               => 'Set slot and loadout limits per member group. 0 = unlimited.',
	'gdloadout_max_slots'                 => 'Max Slots',
	'gdloadout_max_loadouts'              => 'Max Loadouts',
	'gdloadout_builder_title'             => 'Build a Loadout',
	'gdloadout_builder_edit_title'        => 'Edit Loadout',
	'gdloadout_builder_limit_reached'     => "You've reached the maximum number of loadouts for your membership level.",
	'gdloadout_slot_base_firearm'         => 'Base Firearm',
	'gdloadout_slot_optic'                => 'Optic',
	'gdloadout_slot_weapon_light'         => 'Weapon Light',
	'gdloadout_slot_laser'                => 'Laser / Sight',
	'gdloadout_slot_suppressor'           => 'Suppressor',
	'gdloadout_slot_foregrip'             => 'Foregrip / Grip',
	'gdloadout_slot_sling'                => 'Sling',
	'gdloadout_slot_holster'              => 'Holster',
	'gdloadout_slot_ammo'                 => 'Ammunition',
	'gdloadout_slot_cleaning'             => 'Cleaning Kit',
	'gdloadout_slot_extra'                => 'Extra',
	'gdloadout_save_success'              => 'Loadout saved!',
	'gdloadout_error_name_required'       => 'A name is required.',
	'gdloadout_error_over_slot_limit'     => "You've exceeded the maximum number of slots.",
	'gdloadout_error_over_loadout_limit'  => "You've reached the maximum number of loadouts.",
);
