<?php
$lang = [
    '__app_gdrebates'                  => 'GD Rebates',
    'menutab__gdrebates'               => 'GD Rebates',
    'menutab__gdrebates_icon'          => 'tags',
    'menu__gdrebates_rebates'          => 'Rebates',
    /* v1.0.6 — breadcrumb key for the front & admin `rebates` modules.
       Missing key was rendering as raw "module__gdrebates_rebates" on
       /rebates/ pages. */
    'module__gdrebates_rebates'        => 'Rebates',
    'menu__gdrebates_rebates_sources'  => 'Rebate Sources',
    'menu__gdrebates_rebates_settings' => 'Settings',
    'r__sources_manage'                => 'Manage rebate sources',
    'r__settings_manage'               => 'Manage rebate settings',
    'gdrebates_src_manufacturer'       => 'Manufacturer',
    'gdrebates_src_url'                => 'Rebate page URL',
    'gdrebates_src_source_type'        => 'Source type',
    'gdrebates_src_type_single'        => 'Single rebate page',
    'gdrebates_src_type_index'         => 'Index page (links to many)',
    'gdrebates_src_is_active'          => 'Active',
    'gdrebates_src_last_parsed_at'     => 'Last parsed',
    'gdrebates_src_last_status'        => 'Last status',
    'gdrebates_src_add'                => 'Add Source',
    'gdrebates_src_edit'               => 'Edit Source',
    'gdrebates_api_key'                => 'Anthropic API key',
    'gdrebates_parse_cap'              => 'Max sources per parse run',
    'gdrebates_parse_active'           => 'Parsing enabled',
    'gdrebates_model'                  => 'Default Claude model',
    'gdrebates_src_model_override'     => 'Model override',
    'gdrebates_src_parse'              => 'Parse now',
    'gdrebates_src_parse_done'         => 'Parse complete',
    'menu__gdrebates_rebates_queue'    => 'Review Queue',
    'r__queue_manage'                  => 'Manage rebate review queue',
    'gdrebates_rb_edit'                => 'Edit Rebate',
    'gdrebates_rb_manufacturer'        => 'Manufacturer',
    'gdrebates_rb_title'               => 'Title',
    'gdrebates_rb_rebate_type'         => 'Type',
    'gdrebates_rb_amount'              => 'Amount ($)',
    'gdrebates_rb_amount_text'         => 'Amount label',
    'gdrebates_rb_eligible_models'     => 'Eligible models',
    'gdrebates_rb_start_date'          => 'Start date',
    'gdrebates_rb_end_date'            => 'End date',
    'gdrebates_rb_submit_by'           => 'Submit by',
    'gdrebates_rb_redemption_url'      => 'Redemption URL',
    'gdrebates_rb_status'              => 'Status',
    /* v1.0.11 — full rebate_type enum audit. The authoritative list
       lives in modules/admin/rebates/manualadd.php TYPES (9 entries);
       the parser's sanitizeType() collapses uncommon types to 'other'.
       Prior versions were missing gdrebates_type_percent and
       gdrebates_type_gift_card, which rendered as the raw key on
       any card with those types. All 9 keys are now present here
       and re-seeded on upgrade so existing installs get them too. */
    'gdrebates_type_cash'              => 'Cash back',
    'gdrebates_type_percent'           => 'Percent off',
    'gdrebates_type_gift_card'         => 'Gift card',
    'gdrebates_type_prepaid_card'      => 'Prepaid card',
    'gdrebates_type_store_credit'      => 'Store credit',
    'gdrebates_type_free_item'         => 'Free item',
    'gdrebates_type_free_shipping'     => 'Free shipping',
    'gdrebates_type_bundle'            => 'Bundle',
    'gdrebates_type_other'             => 'Other',
    'gdrebates_status_pending'         => 'Pending',
    'gdrebates_status_approved'        => 'Approved',
    'gdrebates_status_rejected'        => 'Rejected',
    'gdrebates_status_expired'         => 'Expired',
    'gdrebates_status_all'             => 'All',
    'gdrebates_approve'                => 'Approve',
    'gdrebates_reject'                 => 'Reject',
    'gdrebates_approved'               => 'Rebate approved',
    'gdrebates_rejected'               => 'Rebate rejected',
    'gdrebates_page_title'             => 'Manufacturer Rebates',
    'gdrebates_f_all_mfr'             => 'All manufacturers',
    'gdrebates_f_all_type'            => 'All types',
    'gdrebates_f_all_amt'             => 'Any amount',
    'gdrebates_sort_ending'           => 'Ending soon',
    'gdrebates_sort_amount'           => 'Highest $',
    'gdrebates_sort_newest'           => 'Newest',
    'gdrebates_ends'                  => 'Ends',
    'gdrebates_submit'                => 'Submit Rebate',
    'gdrebates_details'               => 'Details',
    /* v1.0.7 — primary CTA label when a rebate has no redemption_url
       (falls back to source_url). Keeps every card with a prominent
       action button. */
    'gdrebates_view_offer'            => 'View Offer',

    /* v1.0.9 — model chips (Part 2) */
    'gdrebates_chip_more'             => 'more',
    /* v1.0.11 — collapse label for the now-bidirectional chip toggle. */
    'gdrebates_show_fewer'            => 'Show fewer',
    /* v1.0.10 — front-page checkbox filter, only rendered when
       the ACP show-expired setting is ON (i.e. expired rebates
       can appear at all). */
    'gdrebates_hide_expired'          => 'Hide expired',

    /* v1.0.9 — expiration countdown + expired state (Part 3) */
    'gdrebates_last_day'              => 'Last day!',
    'gdrebates_days_left'             => '%s days left',
    'gdrebates_expired'               => 'Expired',
    'gdrebates_show_expired'          => 'Show expired rebates on the front page',
    'gdrebates_show_expired_desc'     => 'When on, expired rebates stay visible on /rebates/ (grayed out with an "Expired" tag, sorted last). When off, expired rebates are hidden from the front page entirely.',

    /* v1.0.9 — Manual Add Rebate ACP form (Part 1) */
    'menu__gdrebates_rebates_manualadd' => 'Add Rebate',
    'r__manualadd_manage'             => 'Manually add rebates',
    'gdrebates_manual_h_required'     => 'Required',
    'gdrebates_manual_h_amount'       => 'Amount',
    'gdrebates_manual_h_dates'        => 'Dates (optional)',
    'gdrebates_manual_h_models'       => 'Eligible models',
    'gdrebates_manual_h_urls'         => 'URLs (optional)',
    'gdrebates_manual_manufacturer'   => 'Manufacturer',
    'gdrebates_manual_title'          => 'Rebate title',
    'gdrebates_manual_rebate_type'    => 'Type',
    'gdrebates_manual_amount'         => 'Dollar amount (numeric — leave blank for FREE/other)',
    'gdrebates_manual_amount_na'      => 'Not applicable',
    'gdrebates_manual_amount_text'    => 'Amount label (shown on the pill)',
    'gdrebates_manual_start_date'     => 'Start date',
    'gdrebates_manual_end_date'       => 'End date',
    'gdrebates_manual_submit_by'      => 'Submit by',
    'gdrebates_manual_eligible_models' => 'Eligible models — comma-space separated ("Model A, Model B") to match the parser format that drives the chip list',
    'gdrebates_manual_redemption_url' => 'Redemption URL',
    'gdrebates_manual_source_url'     => 'Source page URL',
    'gdrebates_manual_image_url'      => 'Image URL',
    'gdrebates_manual_pdf_url'        => 'PDF URL',
    'gdrebates_manual_save'           => 'Add rebate (goes live immediately)',
    'gdrebates_manual_saved'          => 'Rebate added and published. <a href="%s" target="_blank" rel="noopener">View on /rebates/</a>',
    'gdrebates_manual_err_required'   => 'Manufacturer and title are required.',
    'gdrebates_manual_err_dupe'       => 'A rebate with the same manufacturer + title + end date already exists (matched by dedupe hash). Change the title to disambiguate.',
    'gdrebates_none'                  => 'No active rebates right now. Check back soon.',
    'gdrebates_no_match'              => 'No rebates match those filters.',
    'menu__gdrebates_rebates_logos'    => 'Manufacturer Logos',
    'r__logos_manage'                  => 'Manage manufacturer logos',
    'gdrebates_logo_manufacturer'      => 'Manufacturer',
    'gdrebates_logo_url'               => 'Logo image URL',
    'gdrebates_logo_add'               => 'Add Logo',
    'gdrebates_logo_edit'              => 'Edit Logo',
];
