<ips:template parameters="$items, $orientation='', $carousel=false" />
{expression="\IPS\gddeals\Application::colorCss()" raw="1"}
{{if !empty($items)}}
<header class='ipsWidget__header'>
	<h3>{lang="block_gdRecentComments"}</h3>
</header>
<div class='ipsWidget__content'>
	<i-data>
		<ol class='ipsData ipsData--table ipsData--gd-comments'>
			{{foreach $items as $c}}
			<li class='ipsData__item'>
				<a href='{$c['url']}' class='ipsLinkPanel' tabindex="-1" aria-hidden="true"><span>{$c['deal_title']}</span></a>
				<div class='ipsData__content'>
					<div class='ipsData__main'>
						<h4 class='ipsData__title'><a href='{$c['url']}'>{$c['deal_title']}</a></h4>
						<p class='ipsData__meta'>{$c['author']} &middot; {$c['date']}</p>
						<p class='ipsData__desc'>{$c['snippet']}</p>
					</div>
				</div>
			</li>
			{{endforeach}}
		</ol>
	</i-data>
</div>
{{endif}}
