<ips:template parameters="$loadouts" />
{{if !empty($loadouts)}}
<header class='ipsWidget__header'>
	<h3><i class="fa-solid fa-fire"></i> {lang="gdloadout_trending"}</h3>
</header>
<div class='ipsWidget__content'>
	<i-data>
		<ol class='ipsData ipsData--table ipsData--gd-loadouts'>
			{{foreach $loadouts as $loadout}}
			<li class='ipsData__item'>
				<a href='{$loadout['view_url']}' class='ipsLinkPanel' tabindex="-1" aria-hidden="true"><span>{$loadout['name']}</span></a>
				<div class='ipsData__content'>
					<div class='ipsData__main'>
						<h4 class='ipsData__title'><a href='{$loadout['view_url']}'>{$loadout['name']}</a></h4>
						<p class='ipsData__meta'>{$loadout['owner_name']}</p>
					</div>
					<div class='ipsData__extra'>
						<span class='gd-widget__off'><i class="fa-solid fa-heart"></i> {$loadout['upvotes']}</span>
					</div>
				</div>
			</li>
			{{endforeach}}
		</ol>
	</i-data>
</div>
{{endif}}
