<?php
/* IN_DEV mode mirror of data/lang.xml — kept in sync for in-development
 * convenience. Production language strings are loaded from lang.xml. */
$lang = [
	'__app_gddealer'                     => 'GD Dealer Manager',
	'menutab__gddealer'                  => 'GD Dealers',
	'menutab__gddealer_icon'             => 'store',
	'menu__gddealer_dealers'             => 'Dealer Manager',
	'menu__gddealer_dashboard'           => 'Dealer Dashboard',
	'gddealer_dash_title'                => 'Dealer Manager Dashboard',
	'gddealer_dealers_title'             => 'Dealers',
	'gddealer_mrr_title'                 => 'Monthly Recurring Revenue',
	'gddealer_unmatched_title'           => 'Unmatched UPCs',
	'gddealer_settings_title'            => 'Dealer Manager Settings',
	'gddealer_frontend_dashboard_title'  => 'Dealer Dashboard',
	'gddealer_directory_title'           => 'Dealer Directory',
	'gddealer_directory_subtitle'        => '%1$s active dealers on GunRack.deals',
	'gddealer_directory_no_results'      => 'No dealers found',
	'gddealer_directory_search'          => 'Search dealers...',
	'gddealer_directory_filter_tier'     => 'Tier',
	'gddealer_directory_sort'            => 'Sort By',
	'gddealer_directory_become_dealer'   => 'Become a Dealer',
	'gddealer_front_tab_overview'        => 'Overview',
	'gddealer_front_tab_listings'        => 'Listings',
	'gddealer_front_tab_reviews'         => 'Reviews',
	'gddealer_front_tab_wizard'          => 'Setup Wizard',
	'gddealer_front_tab_feed'            => 'Feed Settings',
	'gddealer_front_tab_validator'       => 'Feed Validator',
	'gddealer_front_tab_unmatched'       => 'Unmatched UPCs',
	'gddealer_front_tab_categories'      => 'Categories',
	'gddealer_front_tab_analytics'       => 'Analytics',
	'gddealer_front_tab_edit_profile'    => 'Edit Profile',
	'gddealer_front_tab_subscription'    => 'Subscription',
	'gddealer_front_tab_help'            => 'Help & Support',
	'gddealer_support_nav'               => 'Support Tickets',
	'gddealer_front_unmatched_intro'     => 'These UPCs appeared in your feed but could not be matched to products in the GunRack catalog.',
	'gddealer_front_export_csv'          => 'Export CSV',
	'gddealer_front_unmatched_empty'     => 'No unmatched UPCs — great work!',
	'gddealer_unmatched_upc'             => 'UPC',
	'gddealer_unmatched_first_seen'      => 'First Seen',
	'gddealer_unmatched_last_seen'       => 'Last Seen',
	'gddealer_unmatched_count'           => 'Count',
	'task__DealerImportFeeds'            => 'Import Dealer Feeds',
];
