<?php

$lang = array(
	/* App + tabs */
	'__app_gdcompliance'                       => 'Compliance',
	'menutab__gdcompliance'                    => 'Compliance',
	'menutab__gdcompliance_icon'               => 'shield-alt',

	/* ACP menu */
	'menu__gdcompliance_compliance_rules'      => 'Rules',
	'menu__gdcompliance_compliance_compute'    => 'Compute Flags',
	'menu__gdcompliance_compliance_roster'     => 'Rosters',
	'menu__gdcompliance_compliance_review'     => 'Review Queue',
	'menu__gdcompliance_compliance_overrides'  => 'Manual Overrides',
	'menu__gdcompliance_compliance_lookup'     => 'Product Lookup',
	'menu__gdcompliance_compliance_browser'    => 'Restrictions Browser',
	'menu__gdcompliance_compliance_awbstates'  => 'AWB States',
	'menu__gdcompliance_compliance_awbmodels'  => 'AWB Master Model List',
	'menu__gdcompliance_compliance_lowers'     => 'Lowers & Receivers',
	'menu__gdcompliance_compliance_magazines'  => 'Magazines',
	'menu__gdcompliance_compliance_advisories' => 'Advisories',
	'menu__gdcompliance_compliance_ammunition' => 'Ammunition',
	'menu__gdcompliance_compliance_knives'     => 'Knives',
	'menu__gdcompliance_compliance_meltingpoint' => 'Melting-Point',
	'menu__gdcompliance_compliance_rof'        => 'Rate-of-Fire Devices',
	'menu__gdcompliance_compliance_settings'   => 'Settings',

	/* v1.6.21 — rate-of-fire enhancer ban (binary triggers, FRTs,
	   bump stocks, trigger cranks) */
	'gdcompliance_acp_rof_title'               => 'Rate-of-Fire Devices',
	'gdcompliance_acp_rof_intro'               => 'Bans on rate-of-fire enhancement devices: binary triggers, forced-reset triggers (FRTs), bump stocks, trigger cranks. Enabled in CA, CT, DE, DC, HI, IL, MA, MD, NJ, NV, NY, OR, RI, WA. ⚠️ MN is NOT enabled — its binary-trigger ban was struck down by the MN Court of Appeals on 2026-05-26. Matcher requires the Franklin Armory brand qualifier for binary/BFS titles (bare "BFS" hits knives, "FRT" hits front sights, "Rare Breed" hits turkey calls). Safe phrases (bump stock, trigger crank) only match inside cat58 Parts & Accessories and cat60 Triggers & Trigger Groups.',
	'gdcompliance_acp_rof_flagged_title'       => 'Flagged devices',
	'gdcompliance_acp_rof_flagged_intro'       => 'Every product currently carrying a rate_of_fire flag. Click a state to filter and reach per-(UPC, state) override — force_clear suppresses the restriction for that product in that state.',
	'gdcompliance_acp_rof_override'            => 'Set override',
	'gdcompliance_acp_rof_curated'             => 'Curated overrides (win over auto-matching)',
	'gdcompliance_acp_rof_curated_intro'       => 'Each row is a substring matched case-insensitive against UPC / title / brand / model / MPN. Use for named makers (Rare Breed Triggers, Fostech Echo, Wide Open Trigger) or to force_clear a false auto-match. force_flag → always flag. force_clear → never flag. review → route to review.',
	'gdcompliance_acp_rof_add'                 => 'Add curated entry',
	'gdcompliance_acp_rof_col_pattern'         => 'Pattern',
	'gdcompliance_acp_rof_col_action'          => 'Action',
	'gdcompliance_acp_rof_col_note'            => 'Note',
	'gdcompliance_rof_f_pattern'               => 'Pattern (case-insensitive substring, matched against UPC/title/brand/model/MPN)',
	'gdcompliance_rof_f_action'                => 'Action',
	'gdcompliance_rof_f_note'                  => 'Note (admin-only) — optional',

	/* v1.6.19 — melting-point handgun ban (HI/IL/MD/MA/MN/NY) */
	'gdcompliance_acp_mp_title'                => 'Melting-Point Handgun Ban',
	'gdcompliance_acp_mp_intro'                => 'Saturday-Night-Special / "melting-point" bans on cheap zinc-alloy handguns — HI / IL / MD / MA / MN / NY. Threshold 800°F (HI/IL/MD/MA/NY) or 1000°F (MN plus tensile/density). Handgun categories only (cat1/2/3); rifles/carbines and non-handgun accessories excluded. Match on the EXACT brand field, never the title (avoids "Heritage Cases" cases, ProMag "Fits Hi-Point" mags, and Cobra rail accessories).',
	'gdcompliance_acp_mp_flagged_title'        => 'Flagged handguns',
	'gdcompliance_acp_mp_flagged_intro'        => 'Every handgun currently carrying a melting_point flag. Click a state to filter and reach per-(UPC, state) override — force_clear suppresses the restriction for that product in that state.',
	'gdcompliance_acp_mp_override'             => 'Set override',
	'gdcompliance_acp_mp_curated'              => 'Curated overrides (win over auto-matching)',
	'gdcompliance_acp_mp_curated_intro'        => 'Each row is a substring matched case-insensitive against UPC / title / brand / model / MPN. force_flag → always flag. force_clear → never flag. review → route to review.',
	'gdcompliance_acp_mp_add'                  => 'Add curated entry',
	'gdcompliance_acp_mp_col_pattern'          => 'Pattern',
	'gdcompliance_acp_mp_col_action'           => 'Action',
	'gdcompliance_acp_mp_col_note'             => 'Note',
	'gdcompliance_mp_f_pattern'                => 'Pattern (case-insensitive substring, matched against UPC/title/brand/model/MPN)',
	'gdcompliance_mp_f_action'                 => 'Action',
	'gdcompliance_mp_f_note'                   => 'Note (admin-only) — optional',

	/* v1.6.17 — buyer-permit advisories (CO / MN). NOT restrictions. */
	'gdcompliance_acp_adv_title'              => 'Buyer-Permit Advisories',
	'gdcompliance_acp_adv_intro'              => 'Advisories are NOT sale restrictions. Each row here means the item CAN ship to that state, but the BUYER must meet a permit / eligibility-card / training step at the FFL. CO covers semi-auto centerfire rifles under SB25-003 (eff. 2026-08-01); MN covers AR/AK-pattern semi-auto rifles under Minn. Stat. §624.712 (in effect since 2023-08-01). Reason text is customer-visible in a yellow advisory block on the product page.',
	'gdcompliance_acp_adv_flagged_title'      => 'Flagged products',
	'gdcompliance_acp_adv_flagged_intro'      => 'Every product currently carrying an advisory flag. Click a state to filter and reach per-(UPC, state) override — a force_clear suppresses the advisory notice for that specific product in that state.',
	'gdcompliance_acp_adv_override'           => 'Set override',

	/* v1.6.47 — Ammunition & Knife state advisories. Same shape as the
	   Buyer-Permit Advisories page above; each row here means the item
	   CAN ship, and the buyer must satisfy the state\'s ammo/knife rules
	   at their end. Reason text ends with "verify current law before
	   purchasing" — informational, not legal advice. */
	'gdcompliance_acp_ammo_title'             => 'Ammunition State Advisories',
	'gdcompliance_acp_ammo_intro'             => 'State-specific ammunition rules — FOID card / eligibility permit / vendor licensing / no-ship jurisdictions. Not sale bans (unless a jurisdiction blocks shipment outright). Each row\'s reason is customer-visible in a yellow advisory block on the ammo product page and always ends with "verify current law before purchasing" — informational, not legal advice.',
	'gdcompliance_acp_ammo_flagged_title'     => 'Flagged ammunition products',
	'gdcompliance_acp_ammo_flagged_intro'     => 'Every product currently carrying an advisory flag (all classes). Click a state to filter and reach per-(UPC, state) override — a force_clear suppresses the advisory for that specific product in that state.',
	'gdcompliance_acp_ammo_override'          => 'Set override',

	'gdcompliance_acp_knife_title'            => 'Knife State Advisories',
	'gdcompliance_acp_knife_intro'            => 'State-specific knife rules — switchblade / automatic / balisong restrictions. Each row\'s reason is customer-visible in a yellow advisory block on the knife product page and always ends with "verify current law before purchasing" — informational, not legal advice.',
	'gdcompliance_acp_knife_flagged_title'    => 'Flagged knife products',
	'gdcompliance_acp_knife_flagged_intro'    => 'Every product currently carrying an advisory flag (all classes). Click a state to filter and reach per-(UPC, state) override — a force_clear suppresses the advisory for that specific product in that state.',
	'gdcompliance_acp_knife_override'         => 'Set override',

	/* v1.6.10 — Lowers ACP */
	'gdcompliance_acp_lowers_title'           => 'Lowers & Receivers',
	'gdcompliance_acp_lowers_intro'           => 'AR/AK-pattern LOWER RECEIVERS are the serialized firearm — treated as an assault-weapon component in the rifle-class AWB states. cat154 flags by default; cat69 is title-gated; bolt/lever/rimfire lowers route to review; parts and uppers are excluded. Add curated overrides below to force-flag or force-clear specific patterns.',
	'gdcompliance_acp_lowers_test'            => 'Test a UPC against the classifier',
	'gdcompliance_acp_lowers_flagged_title'   => 'Flagged Lower Receivers',
	'gdcompliance_acp_lowers_flagged_intro'   => 'Serialized AR/AK-pattern lower receivers currently flagged in gd_compliance_flags (firearm_type=awb_lower). One row per distinct UPC — the "States" count is how many enabled rifle-class AWB states the flag applies to.',
	'gdcompliance_acp_lowers_states_caption'  => 'AR/AK-pattern lower receivers are restricted for sale in each of these states. Click a state to filter the list below and reach per-(UPC, state) overrides — clear or restrict a single lower in a single state.',
	'gdcompliance_acp_lowers_override'        => 'Set override',
	'gdcompliance_acp_lowers_curated'         => 'Curated overrides (win over auto-matching)',
	'gdcompliance_acp_lowers_curated_intro'   => 'Each row is a title/model/MPN/UPC substring, case-insensitive. Curated matches WIN over auto logic. force_flag → always flag. force_clear → never flag. review → route to review queue.',
	'gdcompliance_acp_lowers_add'             => 'Add curated entry',
	'gdcompliance_acp_lowers_col_pattern'     => 'Pattern',
	'gdcompliance_acp_lowers_col_platform'    => 'Platform',
	'gdcompliance_acp_lowers_col_action'      => 'Action',
	'gdcompliance_acp_lowers_col_note'        => 'Note',
	'gdcompliance_lowers_f_pattern'           => 'Pattern (case-insensitive substring, matched against title/brand/model/MPN/UPC)',
	'gdcompliance_lowers_f_platform'          => 'Platform label (e.g. AR-15, AK) — optional',
	'gdcompliance_lowers_f_action'            => 'Action',
	'gdcompliance_lowers_f_note'              => 'Note (shown in the tester, not in flag reasons) — optional',

	/* v1.6.10 — Magazines ACP */
	'gdcompliance_acp_mag_title'              => 'Magazines',
	'gdcompliance_acp_mag_intro'              => 'Standalone MAGAZINE flags (cat38) — a bare LCM classified by caliber and compared against the state\'s handgun / rifle / shotgun limit. Curation is via the per-UPC override list (Overrides) — this page provides the quick "Set override" link for any mis-flagged magazine.',
	'gdcompliance_acp_mag_override'           => 'Set override',

	/* Front module + nav */
	'module__gdcompliance_compliance'          => 'Compliance',
	'frontnavigation_gdcompliance_compliance'  => 'Compliance',

	/* Page titles */
	'gdcompliance_acp_rules_title'             => 'Compliance Rules',
	'gdcompliance_acp_rules_intro'             => 'Edit the state magazine-capacity rules used to flag products. Disabling a rule (or letting expires_date pass) stops it from flagging without deleting the row. A rule applies only when enabled AND inside its effective_date/expires_date window. Capacity strictly greater than max_capacity flags the product.',
	'gdcompliance_acp_rules_add'               => 'Add rule',
	'gdcompliance_acp_rules_reseed'            => 'Reseed missing rules',
	'gdcompliance_acp_rules_reseed_done'      => 'Reseed complete',
	'acplog__gdcompliance_rules_reseeded'      => 'Reseeded canonical compliance rules (non-destructive)',
	'gdcompliance_acp_compute_title'           => 'Compute Compliance Flags',
	'gdcompliance_acp_compute_intro'           => 'Recomputes gd_compliance_flags from gd_catalog × the active rule set. gd_catalog is never modified. Always preview first.',
	'gdcompliance_acp_compute_preview'         => 'Preview (dry run)',
	'gdcompliance_acp_compute_run'             => 'Run / recompute flags',
	'gdcompliance_acp_compute_clear'           => 'Clear all flags',
	'gdcompliance_acp_compute_last'            => 'Last run',
	'gdcompliance_acp_compute_never'           => 'Never',

	/* Compute result panels */
	'gdcompliance_acp_compute_preview_done'    => 'Dry run: would flag {1} products across {2} state-rule pairs.',
	'gdcompliance_acp_compute_run_done'        => 'Computed: flagged {1} products across {2} state-rule pairs.',
	'gdcompliance_acp_compute_cleared'         => 'Cleared {1} flags + {2} unparsed-capacity rows.',
	'gdcompliance_acp_compute_no_rules'        => 'No active rules — enable at least one rule in the Rules tab before computing.',
	'gdcompliance_acp_compute_per_state'       => 'Flags by state',
	'gdcompliance_acp_compute_unparsed'        => 'Unparsed capacity values',
	'gdcompliance_acp_compute_sample'          => 'Sample flagged products',

	/* Rules table column headers (Table\Db langPrefix) */
	'gdcompliance_acp_col_state_code'          => 'State',
	'gdcompliance_acp_col_firearm_type'        => 'Firearm Type',
	'gdcompliance_acp_col_max_capacity'        => 'Limit',
	'gdcompliance_acp_col_rule_type'           => 'Rule Type',
	'gdcompliance_acp_col_effective_date'      => 'Effective',
	'gdcompliance_acp_col_expires_date'        => 'Expires',
	'gdcompliance_acp_col_enabled'             => 'Enabled',
	'gdcompliance_acp_col_source_note'         => 'Source',

	/* Rule form fields */
	'gdcompliance_f_state_code'                => 'State (2-letter)',
	'gdcompliance_f_firearm_type'              => 'Firearm type',
	'gdcompliance_f_max_capacity'              => 'Max capacity (limit)',
	'gdcompliance_f_rule_type'                 => 'Rule type',
	'gdcompliance_f_effective_date'            => 'Effective date (YYYY-MM-DD; blank = always)',
	'gdcompliance_f_expires_date'              => 'Expires date (YYYY-MM-DD; blank = never)',
	'gdcompliance_f_enabled'                   => 'Enabled',
	'gdcompliance_f_source_note'               => 'Source note (citation)',

	/* CA roster (Phase 2) */
	'gdcompliance_acp_roster_title'            => 'CA DOJ Certified Handgun Roster',
	'gdcompliance_acp_roster_intro'            => 'Snapshot of the California Department of Justice Certified Handgun roster. Used by the compute pass to classify catalog handguns into on-roster (CA-legal), off-roster (flagged), or unmatched (review queue). Manual refresh only — never auto-scheduled.',
	'gdcompliance_acp_roster_source'           => 'Source',
	'gdcompliance_acp_roster_last'             => 'Last refreshed',
	'gdcompliance_acp_roster_never'            => 'Never',
	'gdcompliance_acp_roster_total'            => 'Total rows',
	'gdcompliance_acp_roster_current'          => 'Current',
	'gdcompliance_acp_roster_expired'          => 'Expired',
	'gdcompliance_acp_roster_refresh'          => 'Refresh CA Roster',
	'gdcompliance_acp_roster_refresh_ma'       => 'Refresh MA Roster',
	'gdcompliance_acp_roster_refresh_md'       => 'Refresh MD Approved Roster',
	'gdcompliance_acp_roster_refresh_md_dis'   => 'Refresh MD Disapproved List',
	'gdcompliance_acp_roster_import_md'        => 'Import MD CSV',
	'gdcompliance_acp_roster_md_help'          => 'Optional manual export from the MSP Tableau portal. Columns: manufacturer, model (literal "ALL" / "*" / blank → blanket-approved for the whole manufacturer), caliber (optional), list_type (approved | disapproved; default approved). Importing supersedes the PDF-sourced rows for whichever list_type the CSV contains, so you can override either the approved or disapproved list.',
	'gdcompliance_acp_roster_tab_all'          => 'All states',
	'gdcompliance_acp_roster_tab_ca'           => 'CA',
	'gdcompliance_acp_roster_tab_ma'           => 'MA',
	'gdcompliance_acp_roster_tab_md'           => 'MD',
	'gdcompliance_acp_roster_done'             => 'CA roster refreshed: {1} rows ({2} current, {3} expired) across {4} pages.',
	'gdcompliance_acp_roster_ma_done'          => 'MA roster refreshed: {1} rows (extractor: {2}, {3} errors).',
	'gdcompliance_acp_roster_md_pdf_done'      => 'MD approved PDF: {1} rows (as of {2}, {3} split multi-caliber, {4} blanket-caliber, {5} errors).',
	'gdcompliance_acp_roster_md_dis_done'      => 'MD disapproved PDF: {1} rows (as of {2}, {3} errors).',
	'gdcompliance_acp_roster_md_done'          => 'MD CSV imported: {1} rows ({2} blanket, {3} errors).',

	/* Roster column headers (Table\Db langPrefix) */
	'gdcompliance_acp_roster_col_roster_state'    => 'State',
	'gdcompliance_acp_roster_col_list_type'       => 'List',
	'gdcompliance_acp_roster_col_manufacturer'    => 'Manufacturer',
	'gdcompliance_acp_roster_col_model_raw'       => 'Model',
	'gdcompliance_acp_roster_col_caliber'         => 'Caliber',
	'gdcompliance_acp_roster_col_blanket'         => 'All Models',
	'gdcompliance_acp_roster_col_blanket_caliber' => 'Any Caliber',
	'gdcompliance_acp_roster_col_gun_type'        => 'Type',
	'gdcompliance_acp_roster_col_barrel'          => 'Barrel',
	'gdcompliance_acp_roster_col_expired_date'    => 'Expired',
	'gdcompliance_acp_roster_col_date_approved'   => 'Approved',
	'gdcompliance_acp_roster_col_source_label'    => 'Source',
	'gdcompliance_acp_roster_col_as_of_date'      => 'As Of',
	'gdcompliance_acp_roster_col_is_current'      => 'Status',

	/* Review queue — category-aware since v1.6.12 */
	'gdcompliance_acp_review_title'            => 'Compliance Review Queue',
	'gdcompliance_acp_review_intro'            => 'Items pending manual review across every category. Filter by CATEGORY to focus on roster / AWB firearms / lowers / magazines; STATE narrows within a category.',
	'gdcompliance_acp_review_title_all'        => 'Compliance Review Queue',
	'gdcompliance_acp_review_intro_all'        => 'All pending items across categories. Choose a CATEGORY tab to narrow.',
	'gdcompliance_acp_review_title_roster'     => 'Roster Review Queue',
	'gdcompliance_acp_review_intro_roster'     => 'Handguns the matcher could not confidently place on or off a state roster. Each row shows the near-miss roster candidates the matcher considered. Resolve manually — Mark on-roster clears the state restriction for that UPC; Mark off-roster sets the state flag. Decisions persist across recomputes.',
	'gdcompliance_acp_review_title_awb'        => 'AWB Firearm Review Queue',
	'gdcompliance_acp_review_intro_awb'        => 'Semi-auto centerfire firearms flagged for feature-based review (tier-2 or tier-3 AWB). Verify the model / features against the state statute — Confirm AWB writes a force_restrict override; Not an AWB writes a force_clear.',
	'gdcompliance_acp_review_title_lower'      => 'Lower Receiver Review Queue',
	'gdcompliance_acp_review_intro_lower'      => 'Ambiguous cat154 lower receivers (bolt-action / rimfire / unknown platform) needing confirmation. Confirm restricted lower applies a force_restrict override across every enabled rifle-class AWB state; Not an AWB lower clears them all.',
	'gdcompliance_acp_review_title_magazine'   => 'Magazine Review Queue',
	'gdcompliance_acp_review_intro_magazine'   => 'Standalone magazines needing manual review. Confirm over-capacity keeps / adds the state restriction; Not restricted clears it.',
	'gdcompliance_acp_review_title_melting'    => 'Melting-Point Review Queue',
	'gdcompliance_acp_review_intro_melting'    => 'Handguns whose frame material could not be classified from the title. Common case: Heritage Rough Rider models whose title says "Steel Barrel" but has no explicit "Zinc / Alloy Frame" or "Steel Frame" phrase — the frame material may be in the description or MPN. Confirm zinc-alloy frame writes a force_restrict across every enabled melting-point state (HI/IL/MD/MA/MN/NY); Confirm steel frame writes a force_clear across the same set.',
	'gdcompliance_acp_review_mark_confirm_melting' => 'Confirm zinc-alloy frame (restrict)',
	'gdcompliance_acp_review_mark_not_melting'     => 'Confirm steel frame (clear)',
	'gdcompliance_acp_review_pending'          => 'Pending',
	'gdcompliance_acp_review_resolved'         => 'Resolved',
	'gdcompliance_acp_review_mark_on'          => 'Mark on-roster (clear)',
	'gdcompliance_acp_review_mark_off'         => 'Mark off-roster (restrict)',
	'gdcompliance_acp_review_mark_confirm_awb'   => 'Confirm AWB (restrict)',
	'gdcompliance_acp_review_mark_not_awb'       => 'Not an AWB (clear)',
	'gdcompliance_acp_review_mark_confirm_lower' => 'Confirm restricted lower',
	'gdcompliance_acp_review_mark_not_lower'     => 'Not an AWB lower (clear)',
	'gdcompliance_acp_review_mark_confirm_mag'   => 'Confirm over-capacity (restrict)',
	'gdcompliance_acp_review_mark_not_mag'       => 'Not restricted (clear)',
	'gdcompliance_acp_review_reopen'           => 'Re-open for review',
	'gdcompliance_acp_review_candidates'       => 'Near-miss roster candidates',
	'gdcompliance_acp_review_already_resolved' => 'Already resolved',

	/* Review column headers (Table\Db langPrefix) */
	'gdcompliance_acp_review_col_review_type'      => 'Category',
	'gdcompliance_acp_review_col_roster_state'     => 'State',
	'gdcompliance_acp_review_col_upc'              => 'UPC',
	'gdcompliance_acp_review_col_manufacturer'     => 'Manufacturer',
	'gdcompliance_acp_review_col_model_title'      => 'Model / Title',
	'gdcompliance_acp_review_col_caliber'          => 'Caliber',
	'gdcompliance_acp_review_col_suggested_status' => 'Suggested',
	'gdcompliance_acp_review_col_resolved_status'  => 'Resolved as',

	/* Settings labels (audit — referenced but not yet in a Form; seeded
	   preemptively so any future settings ACP form renders proper labels). */
	'gdcompliance_settings_general'            => 'General',
	'gdcompliance_settings_urls'               => 'Roster URLs',
	'gdcompliance_autosync_enabled'            => 'Enable auto-sync',
	'gdcompliance_ma_roster_url'               => 'MA roster PDF URL',
	'gdcompliance_md_roster_url'               => 'MD MSP approved roster PDF URL',
	'gdcompliance_md_disapproved_url'          => 'MD MSP disapproved list PDF URL',
	'gdcompliance_dc_derive'                   => 'DC status derived from CA+MA+MD',

	/* Phase 4 — Overrides */
	'gdcompliance_acp_overrides_title'         => 'Manual Overrides',
	'gdcompliance_acp_overrides_intro'         => 'Per-UPC per-state force restrict / force clear decisions that survive every recompute. Applied AFTER the rule pass on every run, so a rule miss (e.g. an IL-restricted gun the capacity rule doesn\'t catch) or a false positive can be fixed permanently. Deleting an override reverts that UPC+state to pure rule result on the next compute.',
	'gdcompliance_acp_overrides_count'         => 'Total overrides',
	'gdcompliance_acp_overrides_add'           => 'Add override',
	'gdcompliance_acp_overrides_edit'          => 'Edit override',
	'gdcompliance_acp_overrides_save_error'    => 'Could not save override — check upc / state / action.',

	/* Overrides Table\Db column headers */
	'gdcompliance_acp_overrides_col_upc'        => 'UPC',
	'gdcompliance_acp_overrides_col_state_code' => 'State',
	'gdcompliance_acp_overrides_col_action'     => 'Action',
	'gdcompliance_acp_overrides_col_reason'     => 'Reason',
	'gdcompliance_acp_overrides_col_created_by' => 'By',
	'gdcompliance_acp_overrides_col_created_at' => 'When',

	/* Override action labels */
	'gdcompliance_action_force_restrict'       => 'Force restrict (add flag)',
	'gdcompliance_action_force_clear'          => 'Force clear (remove flag)',
	'gdcompliance_f_upc'                       => 'Product UPC',
	'gdcompliance_f_action'                    => 'Override action',
	'gdcompliance_f_reason'                    => 'Reason (shown on the flag)',

	/* Phase 4 — Product lookup */
	'gdcompliance_acp_lookup_title'            => 'Product Lookup',
	'gdcompliance_acp_lookup_intro'            => 'Find a catalog product by UPC or title. See computed flags AND overrides per state, and set force-restrict / force-clear overrides directly from the detail view.',
	'gdcompliance_acp_lookup_search'           => 'UPC or title',
	'gdcompliance_acp_search_go'               => 'Search',
	'gdcompliance_acp_lookup_no_flags'         => 'No restrictions computed for this UPC',

	/* v1.4.1 — Restrictions Browser */
	'gdcompliance_acp_browser_title'           => 'Restrictions Browser',
	'gdcompliance_acp_browser_intro'           => 'Search / filter every product currently flagged in gd_compliance_flags. Filter by state, reason type (capacity / roster / manual override), or free-text (UPC or product title). This is the "what products are actually flagged right now" view.',
	'gdcompliance_acp_browser_q'               => 'UPC or product title',
	'gdcompliance_acp_browser_state'           => 'State',
	'gdcompliance_acp_browser_type'            => 'Type',
	'gdcompliance_acp_browser_showing'         => 'Showing',
	'gdcompliance_acp_browser_empty'           => 'No flagged products match those filters.',

	/* v1.5.2 — Illinois PICA (720 ILCS 5/24-1.9) */
	'gdcompliance_acp_pica_title'              => 'Illinois PICA Named Models',
	'gdcompliance_acp_pica_intro'              => 'Statutory named-model list from 720 ILCS 5/24-1.9(a)(1)(J). Rifles whose title/brand/model/description match ANY enabled pattern (aggressive normalization: strip all non-alphanumeric, lowercase) get a Tier-1 PICA flag with high confidence. Semi-auto rifles that match nothing here still get a Tier-2 "likely PICA — verify" flag for the review queue.',
	'gdcompliance_acp_pica_add'                => 'Add pattern',
	'gdcompliance_acp_pica_reseed'             => 'Reseed statutory list',
	'gdcompliance_acp_pica_reseed_done'        => 'PICA model reseed complete',
	'acplog__gdcompliance_pica_reseeded'       => 'Reseeded PICA statutory model list (non-destructive)',
	'gdcompliance_acp_pica_col_pattern'        => 'Pattern',
	'gdcompliance_acp_pica_col_pattern_norm'   => 'Normalized',
	'gdcompliance_acp_pica_col_platform_group' => 'Platform',
	'gdcompliance_acp_pica_col_citation'       => 'Citation',
	'gdcompliance_acp_pica_col_enabled'        => 'Enabled',
	'gdcompliance_pica_f_pattern'              => 'Pattern (as it appears in catalog titles)',
	'gdcompliance_pica_f_platform_group'       => 'Platform group (e.g. AR-15, AK, SCAR)',
	'gdcompliance_pica_f_citation'             => 'Statutory citation',
	'gdcompliance_pica_f_enabled'              => 'Enabled',
	'gdcompliance_reason_pica'                 => 'PICA (IL)',
	'gdcompliance_reason_awb'                  => 'AWB',

	/* v1.6.1 — AWB States dashboard */
	'gdcompliance_acp_awbstates_title'        => 'AWB States Dashboard',
	'gdcompliance_acp_awbstates_intro'        => 'One row per (state, firearm class). Model counts and flagged-product counts are live. Click "Open" for a state to edit its config, browse its named-model list, and search your catalog for banned/allowed status in that state.',
	'gdcompliance_acp_awbstates_config'       => 'Config',
	'gdcompliance_acp_awbstates_models'       => 'Named models',
	'gdcompliance_acp_awbstates_search'       => 'Check UPC / title against this state',
	'gdcompliance_acp_awbstates_exemption_note' => 'Exemption note (customer disclaimer)',
	'gdcompliance_acp_awbstates_exemption_note_help' => 'Shown in the customer restriction popup below the reason and citation, and in the ACP UPC lookup. The AWB flag stays ON — this is a disclaimer pointing the buyer to verify eligibility with their FFL. Leave blank to hide.',

	/* v1.6.0 — Multi-state Assault Weapons Ban framework */
	'gdcompliance_acp_awb_title'               => 'AWB Named Models',
	'gdcompliance_acp_awb_intro'               => 'Per-state statutory named-model list for the multi-state Assault Weapons Ban framework. Filter by state (IL PICA, CA Pen 30510/30515, NY SAFE Act) or manage all in one view. Rifles whose title/brand/manufacturer/model/description match ANY enabled pattern for a state get a Tier-1 AWB flag for that state.',
	'gdcompliance_acp_awb_add'                 => 'Add pattern',
	'gdcompliance_acp_awb_reseed'              => 'Reseed statutory lists',
	'gdcompliance_acp_awb_reseed_done'         => 'AWB model reseed complete',
	'acplog__gdcompliance_awb_reseeded'        => 'Reseeded AWB statutory named-model lists (non-destructive)',
	'gdcompliance_acp_awb_col_state_code'      => 'State',
	'gdcompliance_acp_awb_col_pattern'         => 'Pattern',
	'gdcompliance_acp_awb_col_pattern_norm'    => 'Normalized',
	'gdcompliance_acp_awb_col_platform_group'  => 'Platform',
	'gdcompliance_acp_awb_col_citation'        => 'Citation',
	'gdcompliance_acp_awb_col_enabled'         => 'Enabled',
	'gdcompliance_awb_f_state_code'            => 'State',
	'gdcompliance_awb_f_pattern'               => 'Pattern (as it appears in catalog titles)',
	'gdcompliance_awb_f_platform_group'        => 'Platform group (e.g. AR-15, AK, SCAR)',
	'gdcompliance_awb_f_citation'              => 'Statutory citation',
	'gdcompliance_awb_f_enabled'               => 'Enabled',

	'gdcompliance_acp_awbrules_title'          => 'AWB Rules (per-state feature-test config)',
	'gdcompliance_acp_awbrules_intro'          => 'One row per (state, firearm class). feature_count_threshold: 1 = single-feature AWB (CA/NY/IL/CT/NJ/WA/DC), 2 = two-feature AWB (MA/MD). centerfire_only: leave on — every state exempts rimfire (.22LR etc.). max_overall_length_in: only set for CA rifles (<30" triggers AWB regardless of features per Pen 30515). effective_date + expires_date: date-gate a rule (RI 2026-07-01 auto-activates; VA seeded disabled during 2025-26 legal flux).',
	'gdcompliance_acp_awbrules_add'            => 'Add rule',
	'gdcompliance_acp_awbrules_reseed'         => 'Reseed statutory rules',
	'gdcompliance_acp_awbrules_reseed_done'    => 'AWB rules reseed complete',
	'acplog__gdcompliance_awbrules_reseeded'   => 'Reseeded AWB per-state rule config (non-destructive)',
	'gdcompliance_acp_awbrules_col_state_code'              => 'State',
	'gdcompliance_acp_awbrules_col_firearm_class'           => 'Class',
	'gdcompliance_acp_awbrules_col_feature_count_threshold' => 'Feature threshold',
	'gdcompliance_acp_awbrules_col_centerfire_only'         => 'Centerfire only',
	'gdcompliance_acp_awbrules_col_max_overall_length_in'   => 'Max OAL (in)',
	'gdcompliance_acp_awbrules_col_effective_date'          => 'Effective',
	'gdcompliance_acp_awbrules_col_expires_date'            => 'Expires',
	'gdcompliance_acp_awbrules_col_enabled'                 => 'Enabled',
	'gdcompliance_acp_awbrules_col_notes'                   => 'Notes',
	'gdcompliance_awbrules_f_state_code'              => 'State',
	'gdcompliance_awbrules_f_firearm_class'           => 'Firearm class',
	'gdcompliance_awbrules_f_feature_count_threshold' => 'Feature-count threshold',
	'gdcompliance_awbrules_f_centerfire_only'         => 'Centerfire only',
	'gdcompliance_awbrules_f_max_overall_length_in'   => 'Max overall length (inches, blank = n/a)',
	'gdcompliance_awbrules_f_citation'                => 'Citation',
	'gdcompliance_awbrules_f_effective_date'          => 'Effective date (YYYY-MM-DD)',
	'gdcompliance_awbrules_f_expires_date'            => 'Expires date (YYYY-MM-DD)',
	'gdcompliance_awbrules_f_enabled'                 => 'Enabled',
	'gdcompliance_awbrules_f_notes'                   => 'Notes',

	/* v1.5.4 — Roster operational */
	'gdcompliance_acp_roster_refresh_all'      => 'Refresh all rosters (CA + MA + MD)',
	'gdcompliance_acp_roster_refresh_all_hint' => 'Sequentially runs every fetcher; per-source failures surface in the flash message so you can see exactly what went wrong.',

	/* v1.6.2 — editable source URLs + upload */
	'gdcompliance_acp_roster_sources_title'    => 'Edit roster source URLs',
	'gdcompliance_acp_roster_save_sources'    => 'Save source URLs',
	'gdcompliance_acp_roster_upload_ma'       => 'Upload MA roster PDF',
	'gdcompliance_acp_roster_upload_md_approved'    => 'Upload MD approved PDF',
	'gdcompliance_acp_roster_upload_md_disapproved' => 'Upload MD disapproved PDF',

	/* Compute overrides summary strip */
	'gdcompliance_acp_compute_overrides'       => 'Overrides applied',

	/* Front page */
	'gdcompliance_page_title'                  => 'State Compliance Rules',
	'gdcompliance_page_intro'                  => 'Active state magazine-capacity restrictions applied to the GunRack catalog.',
	'gdcompliance_page_empty'                  => 'No active rules.',

	/* Phase 5 — Frontend restriction notice (storefront product page) */
	'gdcompliance_front_heading'               => 'Sales Restrictions',
	'gdcompliance_front_intro'                 => 'This item may not be available for sale or shipment into:',
	'gdcompliance_front_disclaimer'            => 'Restrictions are provided as guidance and may not reflect the most current law; verify before purchase.',
	'gdcompliance_front_state_prefix'          => 'Restricted in',
	'gdcompliance_restricted_badge'            => 'Restricted in %d states',
	'gdcompliance_reason_capacity'             => 'Capacity',
	'gdcompliance_reason_roster'               => 'Roster',
	'gdcompliance_reason_override'             => 'Manual',

	/* Phase 5 — ACP settings page */
	'gdcompliance_acp_settings_title'          => 'Frontend Restriction Display',
	'gdcompliance_front_enabled'               => 'Show restriction panel on storefront',
	'gdcompliance_front_enabled_desc'          => 'Master toggle. When off, no "Sales Restrictions" panels render on product pages or grids.',
	'gdcompliance_front_show_reasons'          => 'Show per-state reason on each row',
	'gdcompliance_front_show_reasons_desc'     => 'When off, the panel lists only the state codes; when on, each state shows its detected reason (capacity vs roster vs manual).',
	'gdcompliance_front_disclaimer_desc'       => 'Displayed at the bottom of every restriction panel. FFL guidance framing recommended.',
	'acplog__gdcompliance_settings_saved'      => 'Saved frontend restriction display settings',

	/* v1.6.22 — Public State Compliance Lookup (/state-lookup/) */
	'gdcompliance_acp_settings_lookup_header'  => 'Public State Compliance Lookup (/state-lookup/)',
	'gdcompliance_lookup_enabled'              => 'Publish the /state-lookup/ page',
	'gdcompliance_lookup_enabled_desc'         => 'When off, visitors to /state-lookup/ see a "temporarily unavailable" notice instead of the lookup form.',
	'gdcompliance_lookup_disclaimer'           => 'Public disclaimer',
	'gdcompliance_lookup_disclaimer_desc'      => 'Shown at the top of the /state-lookup/ page. Legal-guidance framing recommended — this is customer-facing.',
	'gdcompliance_lookup_page_title'           => 'State Firearm Compliance Lookup',
	'gdcompliance_lookup_intro'                => 'Pick your state and enter a UPC or MPN to check whether that item is restricted for sale in your state. Read-only against our current catalog.',
	'gdcompliance_lookup_disclaimer_label'     => 'Important Notice',
	'gdcompliance_lookup_default_disclaimer'   => "State Firearm Compliance Lookup — Important Notice. This tool provides general information based on our product catalog and our understanding of current state law. It is not legal advice and is not a guarantee of legality. Firearm laws change frequently, vary by locality, and depend on individual circumstances. A result of 'no restrictions found' means our system did not flag this item for the selected state — it does not affirmatively certify the item is legal for you to purchase or possess. Always verify with your FFL and consult current state and local law before completing any purchase or transfer. Gun Wise LLC assumes no liability for reliance on this tool.",
	'gdcompliance_lookup_field_state'          => 'Ship-to state',
	'gdcompliance_lookup_pick_state'           => 'Pick a state…',
	'gdcompliance_lookup_field_q'              => 'UPC or MPN',
	'gdcompliance_lookup_field_q_ph'           => 'e.g. 022188879834',
	'gdcompliance_lookup_submit'               => 'Look up',
	'gdcompliance_lookup_product'              => 'UPC %s:',
	'gdcompliance_lookup_citation'             => 'Citation: %s',
	'gdcompliance_lookup_restricted_headline'  => 'Restricted for sale in %s',
	'gdcompliance_lookup_advisory_label'       => 'Buyer requirement',
	'gdcompliance_lookup_advisory_headline'    => 'Buyer requirement in %s',
	'gdcompliance_lookup_advisory_intro'       => 'This item can ship. The buyer must meet a state permit / training requirement at the FFL. Not a sale prohibition.',
	'gdcompliance_lookup_norestrict_headline'  => 'No restrictions found in %s',
	'gdcompliance_lookup_clear_body'           => 'No restrictions found for this item in %s.',
	'gdcompliance_lookup_clear_reminder'       => 'This is not a legal guarantee. Verify with your FFL and consult current state and local law before completing any purchase.',
	'gdcompliance_lookup_verify_reminder'      => 'This reflects our current data. Verify with your receiving FFL before purchase.',
	'gdcompliance_lookup_not_found'            => 'We could not find %s in our catalog, so we have no compliance information for it.',
	'gdcompliance_lookup_not_found_hint'       => 'Double-check the UPC / MPN. Only items currently in our catalog are covered by this tool.',
	'gdcompliance_lookup_disabled_msg'         => 'The state-lookup page is temporarily unavailable. Please check back later.',

	/* v1.6.24 — public "report a problem" (login-gated) */
	'gdcompliance_lookup_report_cta'            => 'Report a problem with this result',
	'gdcompliance_lookup_report_login_cta'      => 'Log in to report a classification issue',
	'gdcompliance_lookup_report_login_required' => 'Please log in to submit a report.',
	'gdcompliance_lookup_report_note_label'     => 'Tell us what looks wrong',
	'gdcompliance_lookup_report_note_placeholder' => 'What do you believe is misclassified, and why? Feel free to link a state statute or catalog page.',
	'gdcompliance_lookup_report_submit'         => 'Submit report',
	'gdcompliance_lookup_report_hint'           => 'Reports are reviewed by staff. Corrections can take up to 90 days to be reflected in the catalog. If you are logged in, you will be notified when your report is resolved.',
	'gdcompliance_lookup_report_thanks'         => 'Thank you — your report has been received and will be reviewed. Any resulting correction can take up to 90 days to be reflected in the catalog. You will be notified when your report is resolved.',
	'gdcompliance_lookup_report_ratelimited'    => 'You have submitted several reports recently. Please try again later.',
	'gdcompliance_lookup_report_error'          => 'We could not accept your report. Please check the form and try again.',

	/* v1.6.24 — ACP triage strings */
	'menu__gdcompliance_compliance_reports'     => 'Compliance Reports',
	'gdcompliance_acp_reports_title'            => 'Compliance Reports',
	'gdcompliance_acp_reports_intro'            => 'Member-submitted reports from the public /state-lookup/ page. Resolve a report to create an override that flips the classification on next recompute, or dismiss to close without action. Either action notifies the reporter.',
	'gdcompliance_acp_reports_tab_pending'      => 'Pending',
	'gdcompliance_acp_reports_tab_resolved'     => 'Resolved',
	'gdcompliance_acp_reports_tab_dismissed'    => 'Dismissed',
	'gdcompliance_acp_reports_tab_all'          => 'All',
	'gdcompliance_acp_reports_col_member_id'                 => 'Reporter',
	'gdcompliance_acp_reports_col_upc'                       => 'UPC',
	'gdcompliance_acp_reports_col_state_code'                => 'State',
	'gdcompliance_acp_reports_col_reported_classification'   => 'Reported',
	'gdcompliance_acp_reports_col_note'                      => 'Note',
	'gdcompliance_acp_reports_col_status'                    => 'Status',
	'gdcompliance_acp_reports_col_created_at'                => 'Submitted',
	'gdcompliance_acp_reports_action_resolve'   => 'Resolve',
	'gdcompliance_acp_reports_action_dismiss'   => 'Dismiss',
	'gdcompliance_acp_reports_action_view'      => 'View',
	'gdcompliance_acp_reports_resolve_title'    => 'Resolve report',
	'gdcompliance_acp_reports_dismiss_title'    => 'Dismiss report',
	'gdcompliance_acp_reports_resolve_override' => 'Create catalog override on resolve?',
	'gdcompliance_acp_reports_resolve_override_none'           => 'No override — classification was correct or handled separately.',
	'gdcompliance_acp_reports_resolve_override_force_clear'    => 'Force clear — no restrictions for this UPC in this state.',
	'gdcompliance_acp_reports_resolve_override_force_restrict' => 'Force restrict — this UPC IS restricted in this state.',
	'gdcompliance_acp_reports_resolution_note'      => 'Resolution note (surfaced to the reporter)',
	'gdcompliance_acp_reports_resolution_note_hint' => 'Optional. Kept short — this is delivered inline with the notification.',
	'gdcompliance_acp_reports_cancel'          => 'Cancel',

	/* v1.6.24 — Settings */
	'gdcompliance_report_ratelimit'      => 'Max reports per member per hour',
	'gdcompliance_report_ratelimit_desc' => 'Rate limit for submissions to the /state-lookup/ report form. Login is already required; this backstops spam.',

	/* v1.6.24 — Notification framework strings */
	'gdcompliance_notif_report'                        => 'Compliance report reviewed',
	'gdcompliance_notif_report_desc'                   => 'When staff resolves or dismisses a compliance report you submitted from the /state-lookup/ page.',
	'notification__gdcompliance_report_resolved'       => 'Compliance report resolved',
	'notification__gdcompliance_report_resolved_desc'  => 'Notify me when a compliance report I submitted is resolved.',
	'notification__gdcompliance_report_dismissed'      => 'Compliance report dismissed',
	'notification__gdcompliance_report_dismissed_desc' => 'Notify me when a compliance report I submitted is dismissed.',

	/* v1.6.25 — Stage 3: advanced search + statelist + CSV */
	'gdcompliance_lookup_available_note'  => "This 'available' list reflects items our compliance engine did not flag for the selected state. While our engine catches the vast majority of restrictions, no automated system is ever 100% accurate — it cannot account for every local ordinance, recent law change, or individual circumstance. Always confirm with your local laws and your FFL before purchasing to make sure an item is legal for you in your area.",
	'gdcompliance_lookup_available_note_desc' => 'Verification note shown at the top of the Advanced Search "Available" result view. Customer-facing.',
	'gdcompliance_lookup_csv_max'          => 'CSV export row cap',
	'gdcompliance_lookup_csv_max_desc'     => 'Maximum rows the /state-lookup/ restricted-list CSV export will produce, per state. Backstop against runaway generation.',
	'gdcompliance_lookup_tab_single'       => 'Single Lookup',
	'gdcompliance_lookup_tab_search'       => 'Advanced Search',
	'gdcompliance_lookup_tab_statelist'    => 'Restricted List',
	'gdcompliance_lookup_search_state'     => 'Ship-to state',
	'gdcompliance_lookup_search_category'  => 'Category',
	'gdcompliance_lookup_search_brand'     => 'Brand (optional)',
	'gdcompliance_lookup_search_mode'      => 'Mode',
	'gdcompliance_lookup_search_type'      => 'Restriction type',
	'gdcompliance_lookup_search_run'       => 'Search',
	'gdcompliance_lookup_mode_restricted'  => 'Restricted',
	'gdcompliance_lookup_mode_available'   => 'Available',
	'gdcompliance_lookup_available_warn'   => 'Filter required. The "available" list is too large to render without at least one of Category or Brand set. Pick a category or type a brand.',
	'gdcompliance_lookup_pick_state_msg'   => 'Pick a state to search.',
	'gdcompliance_lookup_pick_state_list'  => 'Pick a state to view its full restricted list.',
	'gdcompliance_lookup_search_no_match'  => 'No items match those filters for %s.',
	'gdcompliance_lookup_statelist_title'  => 'Restricted List',
	'gdcompliance_lookup_csv_download'     => 'Download CSV',
	'gdcompliance_lookup_row_report'       => 'Report a problem',
	'gdcompliance_lookup_row_available_label' => 'Available',

	/* v1.6.27 — CSV export gate + upsell */
	'gdcompliance_csv_allowed_groups'      => 'Groups allowed to download the restricted-list CSV',
	'gdcompliance_csv_allowed_groups_desc' => 'Comma-separated member group IDs. Members in any listed group can download the /state-lookup/ restricted-list CSV; everyone else sees an upsell prompt. Guests always denied. Default seeds the Administrators group.',
	'gdcompliance_csv_upsell_url'          => 'CSV upsell link',
	'gdcompliance_csv_upsell_url_desc'     => 'Where the "Upgrade" button on the CSV upsell block links to. Point at your membership / subscription page. Leave as # to render a disabled "Learn more" label instead of a link.',
	'gdcompliance_csv_upsell_text'         => 'CSV upsell message',
	'gdcompliance_csv_upsell_text_desc'    => 'Text shown to non-allowed visitors in place of the CSV download button.',
	'gdcompliance_csv_upsell_default'      => 'Downloading the full restricted-list CSV is a membership benefit. Upgrade your membership to enable bulk downloads.',
	'gdcompliance_csv_locked_title'        => 'Download CSV — members only',
	'gdcompliance_csv_cta_upgrade'         => 'Upgrade',
	'gdcompliance_csv_cta_learn'           => 'Learn more',

	/* v1.6.28 — Compliance API (Product A) Stage 1 */
	'menu__gdcompliance_compliance_apikeys'  => 'API Keys',
	'gdcompliance_acp_apikeys_title'         => 'Compliance API Keys',
	'gdcompliance_acp_apikeys_intro'         => 'Machine-to-machine keys for /compliance-api/. Each key belongs to a member (dealer) and authenticates JSON requests to /compliance-api/check and /compliance-api/batch. Suspend to temporarily block (returns 402); revoke to permanently block (returns 401).',
	'gdcompliance_acp_apikeys_create'        => 'Create key',
	'gdcompliance_acp_apikeys_create_title'  => 'Create API key',
	'gdcompliance_acp_apikeys_col_label'         => 'Label',
	'gdcompliance_acp_apikeys_col_member_id'     => 'Owner',
	'gdcompliance_acp_apikeys_col_api_key'       => 'Key',
	'gdcompliance_acp_apikeys_col_status'        => 'Status',
	'gdcompliance_acp_apikeys_col_request_count' => 'Requests',
	'gdcompliance_acp_apikeys_col_created_at'    => 'Created',
	'gdcompliance_acp_apikeys_col_last_used_at'  => 'Last used',
	'gdcompliance_acp_apikeys_action_suspend'    => 'Suspend',
	'gdcompliance_acp_apikeys_action_reactivate' => 'Reactivate',
	'gdcompliance_acp_apikeys_action_revoke'     => 'Revoke',

	/* v1.6.45 — member-level API block (hard cut, overrides group + per-key) */
	'gdcompliance_acp_apikeys_action_block'   => 'Block API access',
	'gdcompliance_acp_apikeys_action_unblock' => 'Unblock API access',
	'gdcompliance_acp_apikeys_block_title'    => 'Block API access',
	'acplog__gdcompliance_apikey_block'       => 'Blocked compliance API access for member %s: %s',
	'acplog__gdcompliance_apikey_unblock'     => 'Unblocked compliance API access for member %s',

	'gdcompliance_api_disclaimer'      => 'API response disclaimer',
	'gdcompliance_api_disclaimer_desc' => 'Legal-guidance text embedded in every /compliance-api/ JSON response so it propagates to the dealer\'s frontend (liability chain).',
	'gdcompliance_api_verified'        => 'Data verification: mark data as legally verified',
	'gdcompliance_api_verified_desc'   => 'Off (default): every API response carries verification_status="pending_legal_review". Flip on after your legal review completes to advertise "verified" data to integrating dealers.',

	/* v1.6.30 — Compliance API Stage 2 (subscription gate + self-service) */
	'gdcompliance_api_access_groups'      => 'Member groups granting API access',
	'gdcompliance_api_access_groups_desc' => 'Comma-separated group IDs. IPS Commerce should add subscribers to at least one of these groups (secondary group on the API subscription package) and remove them on lapse — the API gate reads live group membership per request, so no webhook is needed. Admins always pass.',
	'gdcompliance_api_subscription_id'      => 'API subscription package ID',
	'gdcompliance_api_subscription_id_desc' => 'Nexus subscription package ID used to build the subscribe/upsell link in 402 responses and on the self-service key page.',
	'gdcompliance_mykey_page_title'    => 'Your Compliance API Key',
	'gdcompliance_mykey_login'         => 'Log in',
	'gdcompliance_mykey_login_msg'     => 'Please log in to view or generate your API key.',
	'gdcompliance_mykey_upsell_title'  => 'API access requires a subscription',
	'gdcompliance_mykey_upsell_msg'    => 'The Compliance API is a subscription-only integration. Once you subscribe, this page will let you generate and manage your API key.',
	'gdcompliance_mykey_upsell_cta'    => 'View subscription',
	'gdcompliance_mykey_generate_title' => 'Generate your API key',
	'gdcompliance_mykey_generate_msg'   => 'You have an active Compliance API subscription. Generate a key below to start making requests.',
	'gdcompliance_mykey_generate_btn'   => 'Generate API key',
	'gdcompliance_mykey_your_key'       => 'Your API key',
	'gdcompliance_mykey_regen_btn'      => 'Regenerate key',
	'gdcompliance_mykey_regen_confirm'  => 'Regenerating will invalidate the existing key immediately. Any live integrations using it will break until you paste in the new key. Continue?',
	'gdcompliance_mykey_how_title'      => 'How to use it',
	'gdcompliance_mykey_endpoints'      => 'Endpoints',
	'gdcompliance_mykey_envelope'       => 'Response envelope',

	/* v1.6.31 — Stage 3: tier quotas + burst + usage metering */
	'gdcompliance_api_tiers'              => 'Tier quotas (group → monthly requests)',
	'gdcompliance_api_tiers_desc'         => 'JSON object mapping group_id (string) to monthly request quota (int). Example: {"13":10000,"14":100000}. Set a quota of 0 to grant unlimited requests for that tier. Members in multiple tiers get the highest quota.',
	'gdcompliance_api_default_quota'      => 'Default monthly quota',
	'gdcompliance_api_default_quota_desc' => 'Applied when a member is in an API-access group that has no explicit tier mapping. Ignored for admins (always unlimited).',
	'gdcompliance_api_burst_per_sec'      => 'Burst throttle (requests / second / key)',
	'gdcompliance_api_burst_per_sec_desc' => 'Server-protection throttle. Requests above this rate return HTTP 429 rate_limited with Retry-After: 1. Independent of the monthly quota.',
	'gdcompliance_mykey_usage_title'      => 'Usage',
	'gdcompliance_mykey_usage_tier'       => 'Tier',
	'gdcompliance_mykey_usage_quota'      => 'Quota',
	'gdcompliance_mykey_usage_month'      => 'This month',
	'gdcompliance_mykey_usage_reset'      => 'Reset',
	'gdcompliance_mykey_usage_lifetime'   => 'Lifetime',
	'gdcompliance_mykey_usage_upsell'     => 'Approaching your monthly quota. Upgrade your subscription to raise the cap.',
	'gdcompliance_mykey_usage_over'       => 'Monthly quota reached. Further requests will return 429 until reset.',

	/* v1.6.32 — Settings ACP page group headers + missing field labels */
	'gdcompliance_acp_settings_title'        => 'GD Compliance — Settings',
	'gdcompliance_acp_settings_storefront_header' => 'Storefront restriction panel (Phase 5)',
	'gdcompliance_acp_settings_csv_header'   => 'CSV Export Gate — /state-lookup/ restricted-list download',
	'gdcompliance_acp_settings_api_header'   => 'Compliance API — /api/compliance/*',
	'gdcompliance_acp_settings_roster_header' => 'Roster source URLs (CA / MA / MD)',

	'gdcompliance_lookup_csv_max_short'      => 'CSV export row cap',
	'gdcompliance_lookup_csv_max_short_desc' => 'Maximum rows the CSV export produces per state (backstop against runaway generation). Default 50000.',

	'gdcompliance_api_tiers_bad_json'        => 'Tier quotas must be valid JSON. Example: {"13":10000}',
	'gdcompliance_api_tiers_bad_shape'       => 'Each entry must be a positive group id mapped to a non-negative integer quota. Use 0 for unlimited.',
	'gdcompliance_api_verified_warning'      => 'WARNING: only enable after your legal review completes. Flipping this on advertises "verified" data to integrating dealers.',

	'gdcompliance_front_enabled'             => 'Show the storefront restriction panel',
	'gdcompliance_front_show_reasons'        => 'Show reason text on the restriction panel',
	'gdcompliance_front_disclaimer'          => 'Storefront panel disclaimer',

	'gdcompliance_ca_roster_url'             => 'California roster source URL',
	'gdcompliance_ma_roster_url'             => 'Massachusetts roster source URL',
	'gdcompliance_md_roster_url'             => 'Maryland approved-list source URL',
	'gdcompliance_md_disapproved_url'        => 'Maryland disapproved-list source URL',
	'gdcompliance_dc_derive'                 => 'Derive DC restrictions from CA/MA/MD',

	'acplog__gdcompliance_settings_saved'    => 'Updated GD Compliance settings',

	/* Phase 5 — Widget */
	'block_gdRestrictionNotice'                => 'Product Restriction Notice',
	'gdcompliance_widget_upc_fallback'         => 'Fallback UPC (only used if no product UPC in URL)',
);
