<ips:template parameters="$limits" />
<div class="ipsBox">
    <h2 class="ipsBox_title">Loadout Group Limits</h2>
    <table class="ipsTable ipsTable_zebra">
        <thead>
            <tr>
                <th>Group</th>
                <th>Max Loadouts</th>
                <th>Max Slots</th>
            </tr>
        </thead>
        <tbody>
            {{foreach $limits as $limit}}
            <tr>
                <td>{$limit['group_name']}</td>
                <td>{$limit['max_loadouts']}</td>
                <td>{$limit['max_slots']}</td>
            </tr>
            {{endforeach}}
        </tbody>
    </table>
</div>
